kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: azuredisk-standard-retain
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-fileshare-secret
    shareName: db-data
    readOnly: false
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  storageClassName: azuredisk-standard-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400M
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: postgres-pv-volume